### PR TITLE
Add md5 hash property to GSPath

### LINKED ISSUE #482: GSPath md5 hash property could potentially be supported
In the supported methods and properties table in the README, it shows that the `md5` property is only supported for AzureBlobPath, but isnt supported for GSPath.

however there exists a property returned by `bucket.get_blob`: `Blob.md5_hash`
https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.blob.Blob#google_cloud_storage_blob_Blob_md5_hash

so if I understand correctly it should be as simple as updating a line in this dictionary to reflect that, https://github.com/drivendataorg/cloudpathlib/blob/7f1a5dce4277eb2bcd1611389241b818651f9f3a/cloudpathlib/gs/gsclient.py#L119 (and adding a property inside GSPath too)

Happy to submit a PR for it which addresses this and updates docs / tests if this functionality is wanted!!

### PR DESCRIPTION
**Pull request by fafnirZ**
Adding md5 property into GSPath
Updating supported methods and properties in repository root README
Updating LocalGSPath to mimic LocalAzureBlobPath, in that there exists md5 property
Updating mock_gs.MockBlob to include md5_hash property

Closes #482 

----------------

Contributor checklist:

 - [x] I have read and understood `CONTRIBUTING.md`
 - [x] Confirmed an issue exists for the PR, and the text `Closes #issue` appears in the PR summary (e.g., `Closes #123`).
 - [x] Confirmed PR is rebased onto the latest base
 - [ ] Confirmed failure before change and success after change
 - [ ] Any generic new functionality is replicated across cloud providers if necessary
 - [x] Tested manually against live server backend for at least one provider
 - [x] Added tests for any new functionality
 - [x] Linting passes locally
 - [x] Tests pass locally
 - [x] Updated `HISTORY.md` with the issue that is addressed and the PR you are submitting. If the top section is not `## UNRELEASED``, then you need to add a new section to the top of the document for your change.

### CODE REVIEW

**Comment by pjbull** [comment]
Thanks @fafnirZ! Could you CI failures and add a new test?

**Comment by fafnirZ** [comment]
Hey @pjbull, I'm kinda confused as to why my changes has caused so many seemingly unrelated tests to fail on the live server, any chance you could point me in the right direction?

**Comment by pjbull** [comment]
Sorry, as noted here, those are expected since PRs from forks can't access the credentials:
https://cloudpathlib.drivendata.org/stable/contributing/#pr-cicd-test-run

**Comment by fafnirZ** [comment]
Ohhh I missed that section, my bad haha. was getting worried for a second and was thinking I made a big mistake😅.
All goods then! everything seems to look fine then I think?

Thanks for the response btw!
Lmk if there are any issues with this PR! :)

**Pull request merged**
