### PR TITLE
Strictly follow PEP3119 for AnyPath __subclasscheck__ implementation

### PR DESCRIPTION
**Pull request by chbehrens**
The currently implemented subclass check for the AnyPathMeta class results in issubclass(AnyPath, AnyPath) returning False, opposed its expected behavior. With this PR I suggest to switch to the exact implementation shown in [PEP 3119](https://peps.python.org/pep-3119/#overloading-isinstance-and-issubclass). It should resolve this problem while preserving the intended behavior with respect to CloudPath and pathlib.Path.

See https://github.com/drivendataorg/cloudpathlib/issues/246

### CODE REVIEW

**Comment by chbehrens** [comment]
Sorry, I tested it before but messed it up during clean-up. Should be complete now.

**Comment by jayqi** [comment]
I'm wondering if my original decision to use custom `__subclasscheck__` and `__instancecheck__` is the wrong approach here. 

I believe another way of accomplishing what we want (that is also part of PEP 3119) is to have `AnyPath` subclass `abc.ABC` and use [`ABC.register`](https://docs.python.org/3/library/abc.html#abc.ABCMeta.register). This would mean getting rid of our `AnyPathMeta` class since we wouldn't need it, and instead having 

```python
AnyPath.register(Path)
AnyPath.register(CloudPath)
```

I just did a little bit of light testing, and I think it should work equivalently and also resolve the issue of `issubclass(AnyPath, AnyPath)`. 

---

I'm lukewarm on the idea of copying the exact implementation for `__subclasscheck__` and `__instancecheck__` from PEP 3119. PEP 3119 describes those as "naively simple" from-scratch implementations. According to later in PEP 3119:

> The call isinstance(x, C) first checks whether C.__instancecheck__ exists, and if so, calls C.__instancecheck__(x) instead of its normal implementation. Similarly, the call issubclass(D, C) first checks whether C.__subclasscheck__ exists, and if so, calls C.__subclasscheck__(D) instead of its normal implementation.

So that means by doing it this way with `__subclasscheck__` and `__instancecheck__`, we're entirely responsible for the logic of `isinstance` and `issubclass` rather than leaning on any default logic.

**Comment by pjbull** [comment]
I like the implementation @jayqi laid out. @chbehrens would you be willing to take a hack at that version? 

Could you also add a test to the subclass tests to check the bug you filed in #246?

**Comment by pjbull** [comment]
Resolved by #251

**Pull request closed without merging**
