### PR TITLE
Add ability to set endpoint_url from AWS_ENDPOINT_URL env variable

### PR DESCRIPTION
**Pull request by kabirkhan**
Hey guys! Long time :)

Loving this package so far. One minor convenience that might be easier to merge here than this ridiculous upstream PR for the boto3 library.

Allows setting the endpoint_url from the AWS_ENDPOINT_URL env variable while waiting for the upstream PR from boto3: https://github.com/boto/boto3/pull/2746

I'll add a test if the idea works for you guys

### CODE REVIEW

**Comment by pjbull** [comment]
Looks good to me! Test would be great, and then an issue to track removing if/when the upstream issue is resolved.

**Comment by kabirkhan** [comment]
Here's that test

**Comment by kabirkhan** [comment]
Added the issue as well

**Comment by pjbull** [comment]
Test looks good. Can you make sure linting passes? (`make lint` should do that for you locally)

**Comment by kabirkhan** [comment]
Done, not sure why the live tests would be failing though. Doesn't seem to be related to this change.

**Comment by pjbull** [comment]
@kabirkhan yeah, i think that is just that PRs from forks can't use the secrets so live tests can't authenticate. i'll do some digging to see how we enable that.

**Comment by pjbull** [comment]
Dropped these changes on their own branch so we can run the live tests there to confirm

**Pull request merged**
